class_name SystemDB
extends RefCounted
# The STAR CATALOGUE you travel. Each system is its own LOCAL, small-coordinate arena
# (1 unit = 0.1 AU) — you NEVER fly the real interstellar distance, so float precision is
# never stressed. The real light-year distance + sky coordinates are display/transit/
# map metadata only.
#
# Two data sources, unified by id (see _rows):
#   • STARS    — ~45 REAL nearest stars (generated by tools/gen_star_catalog.py from the
#                J2000 nearest-star table). Each cooks from spectral type.
#   • AUTHORED — the hand-built systems with custom planet/live/hostile layouts (Sol live,
#                Proxima b, TRAPPIST-1, K2-18, the imaginary Alien zone).
#
# A "body spec" is what PlanetSystem.load_system() consumes:
#   name, radius (visual), color, glow, model (opt GLB/OBJ), star (bool),
#   live (bool — Sol's Sun/planets read live positions from Ephemeris),
#   pos  (Vector3 local scene units — used when live == false).

const SOL := "sol"
const K2_18 := "k2-18"
const PROXIMA := "proxima"
const TRAPPIST := "trappist"
const ALIEN := "alien"           # the hostile combat zone (Vortex + aliens)
const INTERSTELLAR := "interstellar"   # the deep-space hub between systems

# Catalog stars cook from spectral type. sol.obj is no longer the default sun.

# --- generated by tools/gen_star_catalog.py — real nearest stars (J2000) ---
# Accuracy: hand-transcribed RA/Dec/distance, good to display precision (not science-grade);
# rerun the generator / edit rows to refine. Colour follows spectral class (O/B blue→M red).
static var STARS := [
	{ "id": "alpha_centauri", "name": "Alpha Centauri", "ly": 4.34, "ra": 219.902, "dec": -60.834, "spectral": "G2V", "color": Color(1.00, 0.92, 0.65) },
	{ "id": "barnards_star", "name": "Barnard's Star", "ly": 5.96, "ra": 269.452, "dec": 4.693, "spectral": "M4.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "luhman_16", "name": "Luhman 16", "ly": 6.51, "ra": 162.329, "dec": -53.319, "spectral": "L8", "color": Color(0.72, 0.34, 0.26) },
	{ "id": "wolf_359", "name": "Wolf 359", "ly": 7.86, "ra": 164.122, "dec": 7.015, "spectral": "M6.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "lalande_21185", "name": "Lalande 21185", "ly": 8.30, "ra": 165.834, "dec": 35.970, "spectral": "M2.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "sirius", "name": "Sirius", "ly": 8.71, "ra": 101.287, "dec": -16.716, "spectral": "A1V", "color": Color(0.95, 0.96, 1.00) },
	{ "id": "luyten_726-8", "name": "Luyten 726-8", "ly": 8.77, "ra": 24.755, "dec": -17.950, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_154", "name": "Ross 154", "ly": 9.71, "ra": 282.456, "dec": -23.836, "spectral": "M3.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_248", "name": "Ross 248", "ly": 10.31, "ra": 355.478, "dec": 44.175, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "epsilon_eridani", "name": "Epsilon Eridani", "ly": 10.47, "ra": 53.232, "dec": -9.458, "spectral": "K2V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "lacaille_9352", "name": "Lacaille 9352", "ly": 10.72, "ra": 346.467, "dec": -35.853, "spectral": "M0.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_128", "name": "Ross 128", "ly": 11.01, "ra": 176.935, "dec": 0.804, "spectral": "M4.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ez_aquarii", "name": "EZ Aquarii", "ly": 11.11, "ra": 339.639, "dec": -15.299, "spectral": "M5.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "61_cygni", "name": "61 Cygni", "ly": 11.40, "ra": 316.725, "dec": 38.749, "spectral": "K5.0V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "procyon", "name": "Procyon", "ly": 11.46, "ra": 114.825, "dec": 5.225, "spectral": "F5IV", "color": Color(1.00, 0.98, 0.92) },
	{ "id": "struve_2398", "name": "Struve 2398", "ly": 11.49, "ra": 280.695, "dec": 59.630, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "groombridge_34", "name": "Groombridge 34", "ly": 11.62, "ra": 4.595, "dec": 44.023, "spectral": "M1.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "dx_cancri", "name": "DX Cancri", "ly": 11.68, "ra": 127.456, "dec": 26.777, "spectral": "M6.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "epsilon_indi", "name": "Epsilon Indi", "ly": 11.87, "ra": 330.840, "dec": -56.786, "spectral": "K5V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "tau_ceti", "name": "Tau Ceti", "ly": 11.91, "ra": 26.017, "dec": -15.938, "spectral": "G8.5V", "color": Color(1.00, 0.92, 0.65) },
	{ "id": "gj_1061", "name": "GJ 1061", "ly": 11.98, "ra": 53.999, "dec": -44.513, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "yz_ceti", "name": "YZ Ceti", "ly": 12.12, "ra": 18.127, "dec": -16.999, "spectral": "M4.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "luytens_star", "name": "Luyten's Star", "ly": 12.35, "ra": 111.852, "dec": 5.226, "spectral": "M3.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "teegardens_star", "name": "Teegarden's Star", "ly": 12.50, "ra": 43.254, "dec": 16.881, "spectral": "M6.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "kapteyns_star", "name": "Kapteyn's Star", "ly": 12.83, "ra": 77.919, "dec": -45.018, "spectral": "M1.5VI", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "lacaille_8760", "name": "Lacaille 8760", "ly": 12.95, "ra": 319.314, "dec": -38.867, "spectral": "M0.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "scr_1845", "name": "SCR 1845-6357", "ly": 13.06, "ra": 281.272, "dec": -63.963, "spectral": "M8.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "kruger_60", "name": "Kruger 60", "ly": 13.07, "ra": 336.998, "dec": 57.696, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "denis_1048", "name": "DENIS J1048-3956", "ly": 13.19, "ra": 162.061, "dec": -39.935, "spectral": "M8.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_614", "name": "Ross 614", "ly": 13.36, "ra": 97.347, "dec": -2.814, "spectral": "M4.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "wolf_1061", "name": "Wolf 1061", "ly": 14.05, "ra": 247.575, "dec": -12.662, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "van_maanens_star", "name": "Van Maanen's Star", "ly": 14.07, "ra": 12.291, "dec": 5.389, "spectral": "DZ7", "color": Color(0.86, 0.90, 1.00) },
	{ "id": "gliese_1", "name": "Gliese 1", "ly": 14.17, "ra": 1.352, "dec": -37.358, "spectral": "M1.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "tz_arietis", "name": "TZ Arietis", "ly": 14.58, "ra": 30.055, "dec": 13.052, "spectral": "M4.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "wolf_424", "name": "Wolf 424", "ly": 14.60, "ra": 188.322, "dec": 9.021, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_687", "name": "Gliese 687", "ly": 14.84, "ra": 264.108, "dec": 68.339, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_674", "name": "Gliese 674", "ly": 14.85, "ra": 262.166, "dec": -46.895, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "lhs_292", "name": "LHS 292", "ly": 14.87, "ra": 162.053, "dec": -11.337, "spectral": "M6.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_440", "name": "Gliese 440", "ly": 15.12, "ra": 176.429, "dec": -64.841, "spectral": "DQ6", "color": Color(0.86, 0.90, 1.00) },
	{ "id": "gj_1245", "name": "GJ 1245", "ly": 15.20, "ra": 298.476, "dec": 44.415, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_876", "name": "Gliese 876", "ly": 15.24, "ra": 343.320, "dec": -14.264, "spectral": "M3.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "groombridge_1618", "name": "Groombridge 1618", "ly": 15.89, "ra": 152.842, "dec": 49.454, "spectral": "K7.0V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "gliese_412", "name": "Gliese 412", "ly": 16.00, "ra": 166.369, "dec": 43.527, "spectral": "M1.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ad_leonis", "name": "AD Leonis", "ly": 16.19, "ra": 154.902, "dec": 19.869, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_832", "name": "Gliese 832", "ly": 16.20, "ra": 323.392, "dec": -49.009, "spectral": "M1.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "omicron2_eridani", "name": "Omicron-2 Eridani", "ly": 16.33, "ra": 63.818, "dec": -7.653, "spectral": "K0.5V", "color": Color(1.00, 0.76, 0.42) },
]

# Hand-built systems with custom bodies. Metadata mirrors a STARS row (so the shared
# helpers work); `map` overrides the 2D chart position for the imaginary Alien zone.
static var AUTHORED := [
	{ "id": SOL, "name": "Sol", "ly": 0.0, "ra": 0.0, "dec": 0.0, "spectral": "G2V", "color": Color(1.00, 0.85, 0.30) },
	{ "id": PROXIMA, "name": "Proxima b", "ly": 4.24, "ra": 217.429, "dec": -62.679, "spectral": "M5.5V", "color": Color(1.00, 0.40, 0.24) },
	{ "id": TRAPPIST, "name": "TRAPPIST-1", "ly": 39.0, "ra": 346.622, "dec": -5.041, "spectral": "M8V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": K2_18, "name": "K2-18", "ly": 124.0, "ra": 172.560, "dec": 7.588, "spectral": "M2.5V", "color": Color(1.00, 0.45, 0.28) },
	{ "id": ALIEN, "name": "Alien Zone", "ly": 666.0, "ra": 0.0, "dec": 0.0, "spectral": "—", "color": Color(0.95, 0.15, 0.12), "hostile": true, "map": Vector2(-30.0, -26.0) },
]

static var _by_id := {}   # id -> row (lazy union of AUTHORED + STARS, authored first)

# --- catalogue lookup -------------------------------------------------------
static func _rows() -> Dictionary:
	if _by_id.is_empty():
		for r in AUTHORED:
			_by_id[r.id] = r
		for r in STARS:
			_by_id[r.id] = r
	return _by_id

static func _row(id: String) -> Dictionary:
	return _rows().get(id, {})

# Every travel destination (authored + real stars). The Interstellar hub is NOT a
# catalogue destination — it's the deep-space junction you pass through.
static func all() -> Array:
	return _rows().keys()

static func display_name(id: String) -> String:
	if id == INTERSTELLAR:
		return "Interstellar"
	var r := _row(id)
	return str(r.get("name", id)) if not r.is_empty() else id

# Reverse of display_name: a destination id for a star's display name (for fly-to-arrive from the
# hub, where the sky markers are name-keyed). "" if the name isn't a travel destination.
static func id_for_name(nm: String) -> String:
	for id in _rows():
		if str(_rows()[id].get("name", "")) == nm:
			return id
	return ""

static func light_years(id: String) -> float:
	return float(_row(id).get("ly", 0.0))

static func spectral(id: String) -> String:
	return str(_row(id).get("spectral", ""))

static func star_color(id: String) -> Color:
	return _row(id).get("color", Color(1, 1, 1))

# Hostile systems spawn the always-on alien swarm + Vortex boss. (Per-star GUARDIANS that
# gate discovery are separate — see main._is_guarded.)
static func is_hostile(id: String) -> bool:
	return bool(_row(id).get("hostile", false))


# Real 3D position from Sol in light-years (RA/Dec/distance → cartesian). Used for the
# star-map layout and for distance-scaled transit between any two systems.
static func coord(id: String) -> Vector3:
	var r := _row(id)
	var ra := deg_to_rad(float(r.get("ra", 0.0)))
	var dec := deg_to_rad(float(r.get("dec", 0.0)))
	var d := float(r.get("ly", 0.0))
	return Vector3(d * cos(dec) * cos(ra), d * sin(dec), d * cos(dec) * sin(ra))

# 2D chart position for the star map (equatorial-plane projection of coord). The Alien
# zone uses a hand-set `map` override since it isn't a real sky position.
static func galaxy_pos(id: String) -> Vector2:
	var r := _row(id)
	if r.has("map"):
		return r.map
	var c := coord(id)
	return Vector2(c.x, c.z)


# --- Interstellar hub (unchanged): a fixed, flyable layout of the original gate-suns,
# the navigable IMAGINARY-WORMHOLE field. Real light-years are too far to fly, so the hub
# holds one imaginary wormhole per star, laid out in the star's REAL sky direction at a
# flyable (sqrt-compressed, capped) distance. You navigate to a wormhole and fly through it
# to reach its star. main shows only the wormholes the player KNOWS (visited / unlocked /
# radar-found). ---
const WH_MIN_R := 600.0       # nearest wormhole ring distance in the hub
const WH_MAX_R := 3000.0      # farthest (kept float-safe + flyable)
const WH_PER_SQRTLY := 230.0  # ring distance ≈ this × sqrt(light-years)

# Hub position of a star's imaginary wormhole: its real 3D sky direction × a compressed,
# capped distance (near stars' gates sit closer; far ones further, but all reachable).
static func wormhole_pos(star: String) -> Vector3:
	var dir := coord(star)
	dir = dir.normalized() if dir.length() > 0.001 else Vector3(0, 0, -1)
	var r: float = clampf(sqrt(light_years(star)) * WH_PER_SQRTLY, WH_MIN_R, WH_MAX_R)
	return dir * r

# Every imaginary wormhole (one per star, home excluded — Sol is reached by emergency-home).
# Each: { pos, dest, dest_ly, station }. main filters this to the KNOWN set for
# visibility/navigation. `station` = this wormhole carries a dockable space platform.
static func all_wormholes() -> Array:
	var out := []
	for id in all():
		if id == SOL:
			continue
		out.append({
			"pos": wormhole_pos(id), "dest": id, "dest_ly": light_years(id),
			"station": has_station(id),
		})
	return out

# --- Space-platform network --------------------------------------------------
# ~half the wormholes carry a dockable space platform, picked so they're spread evenly
# across the field — so from any wormhole the nearest platform is close (you teleport
# platform→platform, then fly the short rest). Selection is FIXED catalogue geometry:
# deterministic, no persistence. Algorithm = farthest-point sampling (greedy max-min):
# seed at the platform nearest the hub entry, then repeatedly add the wormhole farthest
# from every platform already chosen — which directly minimises the worst-case "how far
# to the nearest platform" over all wormholes.
const STATION_FRAC := 0.5

static var _station_set := {}   # star id -> true (lazy, see has_station)

static func has_station(star: String) -> bool:
	if star == SOL:
		return false
	if _station_set.is_empty():
		_station_set = _compute_stations()
	return _station_set.has(star)

# A dockable platform you can teleport to. Same as has_station PLUS Sol — Sol carries the
# hand-placed HOME station (not a generic platform, so has_station stays false for it to
# avoid double-spawning one), but it IS a valid teleport destination once you've been home.
static func is_teleport_platform(star: String) -> bool:
	return star == SOL or has_station(star)

static func _compute_stations() -> Dictionary:
	var ids := []
	var pos := {}
	for id in all():
		if id == SOL:
			continue
		ids.append(id)
		pos[id] = wormhole_pos(id)
	var chosen := {}
	if ids.is_empty():
		return chosen
	var target: int = int(round(ids.size() * STATION_FRAC))
	# Seed: the wormhole nearest the hub entry point (home-adjacent coverage first).
	var entry := arrival_pos(INTERSTELLAR)
	var seed_id: String = ids[0]
	var best := INF
	for id in ids:
		var d: float = (pos[id] - entry).length()
		if d < best:
			best = d
			seed_id = id
	chosen[seed_id] = true
	# Greedily add the wormhole farthest from the nearest already-chosen platform.
	while chosen.size() < target:
		var far_id := ""
		var far_d := -1.0
		for id in ids:
			if chosen.has(id):
				continue
			var nd := INF
			for c in chosen:
				nd = minf(nd, (pos[id] - pos[c]).length())
			if nd > far_d:
				far_d = nd
				far_id = id
		if far_id == "":
			break
		chosen[far_id] = true
	return chosen

# --- Wormhole NETWORK: a connected graph of point-to-point links --------------
# Wormholes are rewards, not a single field — each system hosts only its few graph
# NEIGHBOURS, and you hop system→system, routing multi-hop over the links you know
# ("go to Proxima first, then Alpha"). Built from the real 3D coords: a minimum spanning
# tree backbone (guarantees EVERY star is reachable from Sol — the whole point of the game)
# plus a few extra short edges for alternate routes. Links are bidirectional.
const WH_HUBS := 5            # spread-out wormhole hubs (each linked to Earth + to each other)

static var _adj := {}          # id -> Array[ neighbour id ]  (lazy, see _ensure_graph)
static var _edges := []        # Array[ [a, b] ]  with a,b ids (each link once)

static func _ensure_graph() -> void:
	if not _adj.is_empty():
		return
	# MULTI-HUB hub-and-spoke (≤ 3 hops to anywhere), instead of a deep MST tree:
	#   • Earth (Sol) is the home anchor, linked to all WH_HUBS hubs           (Earth→hub = 1)
	#   • the hubs are fully interconnected                                     (hub↔hub = 1)
	#   • every other system hangs off its NEAREST hub                          (hub→star = 1)
	# So Earth→any = 2, and any star→any star = 3 (A→hubA→hubB→B). Hubs are chosen spread out
	# (farthest-point sampling, kept away from Sol) so they're not all bunched in one place,
	# and the ~50 systems split across 5 hubs so no single hub carries the whole field.
	var ids := all() + [INTERSTELLAR]
	var pos := {}
	for id in ids:
		_adj[id] = []
		pos[id] = Vector3(0.0, 3.0, 0.0) if id == INTERSTELLAR else coord(id)
	# Hub candidates: every real destination except Sol.
	var pool := []
	for id in all():
		if id != SOL:
			pool.append(id)
	# Seed the hub set with the system FARTHEST from Sol, then repeatedly add the system
	# whose nearest already-chosen hub (and Sol) is farthest away → well-spread hubs.
	var hubs := []
	var seed := ""
	var sd := -1.0
	for id in pool:
		var d: float = pos[SOL].distance_to(pos[id])
		if d > sd:
			sd = d; seed = id
	if seed != "":
		hubs.append(seed)
	while hubs.size() < WH_HUBS and hubs.size() < pool.size():
		var best := ""
		var best_min := -1.0
		for id in pool:
			if hubs.has(id):
				continue
			var mind: float = pos[SOL].distance_to(pos[id])
			for h in hubs:
				mind = minf(mind, pos[h].distance_to(pos[id]))
			if mind > best_min:
				best_min = mind; best = id
		if best == "":
			break
		hubs.append(best)
	var is_hub := {}
	for h in hubs:
		is_hub[h] = true
	# Earth → every hub, and the Interstellar gate stays a home-adjacent node.
	for h in hubs:
		_link(SOL, h)
	_link(SOL, INTERSTELLAR)
	# Fully interconnect the hubs (complete graph) → any hub reaches any hub in one jump.
	for i in hubs.size():
		for j in range(i + 1, hubs.size()):
			_link(hubs[i], hubs[j])
	# Every remaining system hangs off a hub — assigned to its NEAREST hub that still has room.
	# A spoke cap (≈ systems / hubs) keeps the load balanced so no single hub hoards the field;
	# overflow spills to the next-nearest hub. Hop guarantee is unaffected (all hubs interlink).
	var spokes := []
	for id in ids:
		if id != SOL and not is_hub.has(id):
			spokes.append(id)
	var cap: int = int(ceil(float(spokes.size()) / float(maxi(hubs.size(), 1))))
	var load := {}
	for h in hubs:
		load[h] = 0
	for id in spokes:
		var order: Array = hubs.duplicate()
		order.sort_custom(func(a, b): return pos[a].distance_to(pos[id]) < pos[b].distance_to(pos[id]))
		var chosen: String = order[0]
		for h in order:
			if load[h] < cap:
				chosen = h
				break
		_link(id, chosen)
		load[chosen] += 1

static func _link(a: String, b: String) -> void:
	if not _adj[a].has(b):
		_adj[a].append(b)
	if not _adj[b].has(a):
		_adj[b].append(a)
	_edges.append([a, b])

# The systems this one links to directly (its hosted wormholes).
static func neighbors(id: String) -> Array:
	_ensure_graph()
	return _adj.get(id, [])

# Every link in the network, as [a, b] id pairs (each once) — for the map's lane lines.
static func wh_edges() -> Array:
	_ensure_graph()
	return _edges

# Shortest-path NEXT HOP from `from` toward `to` over links the player KNOWS. `known` is an
# optional Callable(a, b) -> bool gating each edge (omit = full graph). "" if no known route.
static func next_hop(from: String, to: String, known := Callable()) -> String:
	if from == to or from == "" or to == "":
		return ""
	_ensure_graph()
	var prev := { from: "" }
	var q := [from]
	while not q.is_empty():
		var cur: String = q.pop_front()
		if cur == to:
			break
		for nb in _adj.get(cur, []):
			if prev.has(nb):
				continue
			if known.is_valid() and not known.call(cur, nb):
				continue
			prev[nb] = cur
			q.append(nb)
	if not prev.has(to):
		return ""
	var path := []
	var node := to
	while node != "":
		path.append(node)
		node = prev.get(node, "")
	path.reverse()
	return path[1] if path.size() >= 2 and path[0] == from else ""


# The hub has NO sun-bodies — it IS the wormhole field; the portals (Wormhole node) are the
# only objects out here, plus the fixed starfield backdrop.
static func _interstellar() -> Array:
	return []


# Short arrival lore (shown once, the first time you reach a system). Empty = no card.
static func lore(id: String) -> String:
	return {
		PROXIMA: "The nearest other sun — a dim red coal 4.24 light-years out, and the\nfirst light most pilots ever claim that isn't our own. Proxima b huddles\nclose to its fire, scorched on one face and frozen on the other.",
		TRAPPIST: "An ultra-cool dwarf with seven worlds packed tight around it, close\nenough that from one you'd see the others as moons. The Survey sends\nits steady hands here — a lot of beacons to plant, all within reach.",
		K2_18: "124 light-years out: a sub-Neptune in its star's temperate lane, the\nkind of world the old telescopes argued over for decades. A long haul\nfor one line in the Atlas — but it's a line few names are on.",
		ALIEN: "Past the safe lanes. The hostiles drift here, and among them Vortex —\nan alien hull grown monstrous, lit with a red menace the dark can't\nswallow. The deep catalog lies on the far side of him. Fly armed.",
		INTERSTELLAR: "The deep between the stars — every charted sun hangs here as a gate.\nPick a light and dive into it. From here the whole network is open.",
	}.get(id, "")

# Where the ship emerges (small local coord) when arriving in a system. Catalogue stars
# (not listed) get a sensible default just off the star.
const PORTAL_LOCAL_R_SOL := 80000.0   # 80,000 km from Earth — outside the planet, still findable

static func arrival_pos(id: String) -> Vector3:
	if id == SOL:
		return Ephemeris.geo_start_pos()
	return {
		K2_18: Vector3(30.0, 6.0, -25.0),
		PROXIMA: Vector3(25.0, 5.0, -30.0), TRAPPIST: Vector3(32.0, 6.0, -35.0),
		ALIEN: Vector3(0.0, 15.0, -70.0),
		INTERSTELLAR: Vector3(0.0, 200.0, 600.0),   # emerge just "south" of the Sol gate-sun
	}.get(id, Vector3(28.0, 6.0, -34.0))

# Wormhole portals = this system's GRAPH NEIGHBOUR links, each placed in local space in the
# real sky DIRECTION of the system it leads to (so the gate to Alpha sits where Alpha is).
# dest_ly = the real light-year HOP distance (drives transit time). main filters these to the
# links the player KNOWS before showing them (see main._known_portals).
const PORTAL_LOCAL_R := 2600.0   # how far out (local units) the gates sit from the star
static func portals(id: String) -> Array:
	_ensure_graph()
	var out := []
	var base := coord(id) if id != INTERSTELLAR else Vector3(0.0, 3.0, 0.0)
	var nbs := neighbors(id)
	var i := 0
	for nb in nbs:
		var nb_coord := coord(nb) if nb != INTERSTELLAR else Vector3(0.0, 3.0, 0.0)
		var dir := nb_coord - base
		dir = dir.normalized() if dir.length() > 0.001 else Vector3(0.0, 0.0, -1.0)
		# Spread gates in height so near-parallel directions don't overlap.
		var gate_r: float = PORTAL_LOCAL_R_SOL if id == SOL else PORTAL_LOCAL_R
		var lift := 220.0 * (float(i) - (nbs.size() - 1) * 0.5)
		if id == SOL:
			lift *= 80.0
		out.append({
			"pos": dir * gate_r + Vector3(0.0, lift, 0.0),
			"dest": nb,
			"dest_ly": maxf(base.distance_to(nb_coord), 0.1),
		})
		i += 1
	return out


static func bodies(id: String) -> Array:
	match id:
		INTERSTELLAR: return _interstellar()
		SOL:      return _sol()
		K2_18:    return _k2_18()
		PROXIMA:  return _proxima()
		TRAPPIST: return _trappist()
		ALIEN:    return _alien()
		_:        return [_single_star(_row(id))]


# A real catalogue star: the cook paints it from spectral type. No hand mesh.
static func _single_star(r: Dictionary) -> Dictionary:
	var b: Dictionary = PlanetGenerator.catalog_star(r)
	b["live"] = false
	b["pos"] = Vector3.ZERO
	return b


# Sol: the live bodies from Ephemeris (Sun + planets), tagged live so
# PlanetSystem reads their real Horizons positions each frame.
static func _sol() -> Array:
	return sol_from(Ephemeris.live_worlds())


# Spawn specs for the Sol cook. Keeps parent so moons stay moons.
static func sol_from(worlds: Array) -> Array:
	var out := []
	# Sol worlds: live JPL planets + 1:1 moons. Voyagers stay out this pass.
	for p in worlds:
		if p.get("craft", false):
			continue
		var b := {
			"name": p.name, "radius": p.radius, "color": p.color,
			"glow": p.get("glow", 1.0), "star": p.get("star", false),
			"mass": p.get("mass", 1.0),
			"ring": p.get("ring", false),
			"craft": p.get("craft", false),
			"drift": p.get("drift", 0.0),
			"live": true, "pos": Vector3.ZERO,
			"physical": p.get("physical", false),
		}
		if p.has("model"):
			b["model"] = p.model
		if p.has("parent"):
			b["parent"] = p.parent
		out.append(b)
	return out


# K2-18: a real M-dwarf (~124 ly) with its real planets. K2-18b is the famous
# sub-Neptune "hycean" candidate at 0.143 AU; K2-18c orbits inside it at 0.067 AU.
static func _k2_18() -> Array:
	return [
		{ "name": "K2-18",  "radius": 6.0, "mass": 120000.0, "color": Color(1.0, 0.45, 0.28), "glow": 2.0,
			"star": true, "live": false, "pos": Vector3(0, 0, 0), "spectral": "M2.5V" },
		{ "name": "K2-18b", "radius": 3.8,  "color": Color(0.32, 0.62, 0.78), "glow": 0.5,
			"star": false, "live": false, "pos": Vector3(12.0, 1.0, 8.0) },   # 0.143 AU
		{ "name": "K2-18c", "radius": 2.0,  "color": Color(0.75, 0.6, 0.5),   "glow": 0.35,
			"star": false, "live": false, "pos": Vector3(-5.5, 0.5, 4.0) },   # 0.067 AU
	]


# Proxima Centauri (~4.24 ly) and its planet Proxima b.
static func _proxima() -> Array:
	return [
		{ "name": "Proxima Centauri", "radius": 5.0, "mass": 40000.0, "color": Color(1.0, 0.4, 0.24), "glow": 2.0,
			"star": true, "live": false, "pos": Vector3(0, 0, 0), "spectral": "M5.5V" },
		{ "name": "Proxima b", "radius": 3.2, "color": Color(0.62, 0.46, 0.40), "glow": 0.4,
			"star": false, "live": false, "pos": Vector3(4.9, 0.6, 3.0) },   # ~0.0485 AU
	]


# TRAPPIST-1 (~39 ly): an ultra-cool red dwarf with several tightly-packed worlds.
static func _trappist() -> Array:
	return [
		{ "name": "TRAPPIST-1", "radius": 3.8, "mass": 30000.0, "color": Color(1.0, 0.5, 0.30), "glow": 2.0,
			"star": true, "live": false, "pos": Vector3(0, 0, 0), "spectral": "M8V" },
		{ "name": "TRAPPIST-1b", "radius": 1.6, "color": Color(0.78, 0.5, 0.42), "glow": 0.35,
			"star": false, "live": false, "pos": Vector3(1.1, 0.2, 0.5) },
		{ "name": "TRAPPIST-1d", "radius": 1.5, "color": Color(0.55, 0.62, 0.7),  "glow": 0.35,
			"star": false, "live": false, "pos": Vector3(-1.8, 0.3, 1.2) },
		{ "name": "TRAPPIST-1e", "radius": 1.7, "color": Color(0.35, 0.62, 0.78), "glow": 0.4,
			"star": false, "live": false, "pos": Vector3(2.2, 0.4, -1.8) },
		{ "name": "TRAPPIST-1g", "radius": 1.9, "color": Color(0.6, 0.6, 0.65),   "glow": 0.35,
			"star": false, "live": false, "pos": Vector3(-3.0, 0.5, -2.2) },
	]


# The hostile zone — a dim, blood-red star to fight under. Aliens + Vortex live here.
static func _alien() -> Array:
	return [
		{ "name": "Hostile Star", "radius": 5.25, "mass": 50000.0, "color": Color(0.9, 0.12, 0.12), "glow": 1.6,
			"star": true, "live": false, "pos": Vector3(0, 0, 0), "spectral": "M" },
		# The deep-catalog nebula — a big, soft, colourful glow out past the hostiles.
		{ "name": "Veil Nebula", "radius": 160.0, "color": Color(0.65, 0.40, 0.95), "glow": 1.3,
			"mass": 0.0, "star": false, "live": false, "pos": Vector3(420.0, 90.0, -560.0) },
	]
