#!/usr/bin/env python3
"""Build a Godot-safe Dingo57 OBJ without changing any geometry.

The supplied OBJ has 352 groups and 678 material switches, which exceeds Godot's
256-surface ArrayMesh limit and truncates the hull. This builder groups all ordinary
faces by authored material and keeps the eight user-identified booster groups as
dedicated surfaces. Vertex/UV/normal/face records are copied exactly; only face order
and surface metadata change.
"""

from __future__ import annotations

import argparse
import re
import zipfile
from collections import OrderedDict
from pathlib import Path


BOOSTER_GROUPS = {"Group_113", "Group_111", "Group_115", "Group_070",
                  "Group_109", "Group_072", "Group_076", "Group_074"}
DOUBLE_SIDED_GROUPS = {"Group_107", "Group_068"}

def clean_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value)


def build(source: Path, output: Path, material_output: Path) -> tuple[int, int, int]:
    attributes: list[str] = []
    buckets: OrderedDict[str, list[str]] = OrderedDict()
    current_group = ""
    current_material = "skp_front_default"
    triangle_count = 0

    if source.suffix.lower() == ".zip":
        with zipfile.ZipFile(source) as archive:
            obj_names = [name for name in archive.namelist() if name.lower().endswith(".obj")]
            if len(obj_names) != 1:
                raise ValueError("expected exactly one OBJ in %s" % source)
            source_lines = archive.read(obj_names[0]).decode("utf-8-sig").splitlines()
    else:
        source_lines = source.read_text(encoding="utf-8-sig").splitlines()
    for raw in source_lines:
        line = raw.rstrip()
        fields = line.split()
        if not fields:
            continue
        token = fields[0]
        if token in {"v", "vt", "vn", "vp"}:
            attributes.append(line)
        elif token == "g" and len(fields) > 1:
            current_group = fields[1]
        elif token == "usemtl" and len(fields) > 1:
            current_material = fields[1]
        elif token == "f":
            if current_group in BOOSTER_GROUPS:
                key = "booster_group_%s" % current_group.removeprefix("Group_")
            elif current_group in DOUBLE_SIDED_GROUPS:
                # Keep these two mirrored hull pieces isolated. Their authored
                # winding is only visible from one side in Godot, so the runtime
                # styling pass gives just these surfaces two-sided culling.
                key = "double_sided_group_%s" % current_group.removeprefix("Group_")
            else:
                key = "hull_%s" % clean_name(current_material)
            buckets.setdefault(key, []).append(line)
            triangle_count += len(fields) - 3

    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("# Godot-safe derived mesh; generated by tools/build_dingo57_obj.py\n")
        stream.write("# Geometry records are copied from the supplied Dingo57 OBJ; hull materials stay default.\n")
        stream.write("mtllib %s\n\n" % material_output.name)
        stream.write("\n".join(attributes))
        stream.write("\n")
        for key, faces in buckets.items():
            material = key.removeprefix("hull_") if key.startswith("hull_") else key
            stream.write("\no %s\nusemtl %s\ns 1\n" % (key, material))
            stream.write("\n".join(faces))
            stream.write("\n")

    with material_output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("# Booster-only materials. The downloaded archive omitted its\n")
        stream.write("# referenced 3d-model.mtl, so hull materials remain untouched/default.\n\n")
        material_blocks = []
        for group in sorted(BOOSTER_GROUPS):
            name = "booster_group_%s" % group.removeprefix("Group_")
            material_blocks.append("newmtl %s\nKd 1 1 1\nKs 1 1 1\nNs 128\nd 1" % name)
        stream.write("\n\n".join(material_blocks) + "\n")

    return len(buckets), triangle_count, len(attributes)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("material_output", type=Path)
    args = parser.parse_args()
    surface_count, triangles, attributes = build(args.source, args.output, args.material_output)
    print("surfaces=%d triangles=%d expected_indices=%d attributes=%d" %
          (surface_count, triangles, triangles * 3, attributes))


if __name__ == "__main__":
    main()
